using DivitOtoyol.Modules.Statistics.LocationStatistics.Dtos;

namespace DivitOtoyol.Modules.Statistics.LocationStatistics.Features.CreatingLocationStatistic;

public record CreateLocationStatisticResponse(LocationStatisticDto LocationStatistic);
